# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ae6fad7893fa00afa3181126ddff981f8cc704fa42a710e405f43701fa47fe28612cd81e96188ec6d29bb3bd6a28bd186a3282994e8eed83c24375b3058f9e9

test:
  secret_key_base: c1dadd591fe6338576cd1543758cb81656cf239ee83608851a9c0676531c0e8565ed35100d5132f7daecf2e3ded65a938d8265fb6693cb2986c62331b9240390

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
